### ISSUE TITLE
Naming of Icons

### ISSUE THREAD

**Issue by aulneau** [plotly/plotly-icons#5]
So as I have been working on this, I had a thought/concern about renaming the MDI imports.

I typical workflow for me when I am using mdi-react, is to go -> https://materialdesignicons.com/ and find an icon that I want to use.  Let's say I wanted to use: `clipboard-arrow-left`. I know that to import it, I'd just do `import ClipboardArrowLeftIcon from 'mdi-react/ClipboardArrowLeftIcon`. 

I'd like to chat about it if makes sense to create a digression between the naming of the mdi-icons and the icons we export from 'plotly-icons'.

Ideally we'd be able to `export * from 'mdi-react'`, in some fashion, so we can automatically import any icon we want from `plotly-icons` via mdi, and then export custom icons we keep in `plotly-icons`.

cc @VeraZab @bpostlethwaite

**Comment by bpostlethwaite** [comment]
My motivations are that we should be able to switch from `mid-react` to another source of icons and maintain the same outward API. That is changing a dependency shouldn't force us to change any code in the webapp. That is how our current icon dependencies work. We maintain css classes in the webapp and can change the icon that it points to with no changes to JS.
Similarly we should be free to generate our own particular icon to replace a `mdi` icon with no change in outward API. There are only a few icons in this repo but there are tens of thousands of lines of code that will be using it.

If folks want `mdi` icons they can simply use `mdi-react`. I prefer to future-proof ourselves behind a layer of indirection. 

The hard work will be integrating this into the webapp. It will be easier if the icons have `webapp` like names rather than `mdi` like names. 

I may have missed the mark or perhaps we can support both. Let me know.

**Comment by bpostlethwaite** [comment]
I can imagine copying `mdi-react` icons _into_ this repo (if licensing permits I need to check this) and removing the dependency completely. That way we have all the svg right here.

**Comment by VeraZab** [comment]
well, I mean, I changed the naming from mdi-names to more webapp like names, so that's already what I thought to be the best thing to do. : ) 

Not just because we can use more webapp like names, but also because we can chose names that better describe the purposes for which we chose a certain icon. For example, what we currently have as the 'cog' icon is named a settings icon in mdi. That naming hints a little to the usage of the icon, and that's not an icon that we use in settings in our editor.

![screen shot 2018-01-02 at 4 49 18 pm](https://user-images.githubusercontent.com/4257572/34501435-f31d4f62-efdc-11e7-8ca9-227d7fb66f45.png)

**Comment by aulneau** [comment]
Thanks for your replies!

I hadn't really considered the idea of if we wanted to switch from `mdi-react` to something else. I agree with that, and I think bringing the icons(svgs) into the repo itself makes a lot of sense. 

Regarding naming: I agree with changing things that have specific actions associated with them, eg: settings -> cog. I guess I was curious more about moving from something like `Chevron..` to `Angle..` as I feel like that just adds a layer of naming change that doesn't really change the meaning of the name. 

As I've been going through the unified font file that `streambed` is using, I understand more where these names have come from, and I am okay with cherry picking svgs from MDI and giving them more 'streambed' like names.

My nexts steps will be to go through all the svgs I've generated from the unified font and then see which ones we could easily swap out with crisper icons from MDI.

Regarding pulling in the SVGs: 
The `mdi-react` repo just pulls the svgs from [here](https://github.com/Templarian/MaterialDesign-SVG) and these are the [licenses for the icons](https://github.com/Templarian/MaterialDesign#license).

**Comment by levrik** [comment]
@VeraZab Maybe levrik/mdi-react#22 can help there 🙂

**Comment by VeraZab** [comment]
oh this is nice, thank you @levrik

**Comment by levrik** [comment]
@VeraZab Just subscribe to the linked issue to be notified as soon as this is done 🙂 
(should be done by the end of the weekend)

**Comment by levrik** [comment]
@VeraZab This is now available in mdi-react 3.3.0
